name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_NUMBER: ${{ github.run_number }}
      SECRETS_TOKEN: ${{ secrets.SECRETS_TOKEN }}

    steps:
      - name: Checkout to main project repo
        uses: actions/checkout@v4
        with:
          path: project

      - name: Checkout secrets repo
        uses: actions/checkout@v4
        with:
          repository: michmadheo/github_actions_flutter_demo_secrets
          ref: refs/heads/master
          token: ${{ env.SECRETS_TOKEN }}
          path: secrets

      - name: Copy build keys to project
        run: |
          cp secrets/key.properties project/android/
          cp secrets/android-keystore.jks project/android/app/

      - name: Build Number
        run: echo "Build number is $BUILD_NUMBER"

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install flutter 3.29.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Fetch flutter packages
        run: |
          cd project
          flutter pub get

      - name: Build Android APK
        run: |
          cd project
          flutter build apk

      - name: Upload Buiild to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: project/build/app/outputs/flutter-apk/app-release.apk
