name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Number
        run: echo "Build number is $BUILD_NUMBER"

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install flutter 3.29.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Fetch flutter packages
        run: flutter pub get
